---
- name: Base packages
  hosts: pis

  tasks:
  - name: Install base packages
    become: yes
    apt:
        name:
          - dphys-swapfile
          - screen
          - vim
          - pigpio
          - gpiod
          - python3-pip
        update_cache: yes
        cache_valid_time: 3600
...
