all:
  vars:
    ansible_python_interpreter: /usr/bin/python3

  children:
    local:
      hosts:
        localhost:
          ansible_connection: local

    fischertechnik:
      vars:
        ansible_user: pi
        ansible_ssh_pass: raspberry
        ansible_ssh_extra_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
        ftc_user: ftc
        ftc_group: ftc
      children:
        tx_pis:
          hosts:
            tx-pi.local:
            tx-pi3.local:
            tx-pi4.local:
            tx-pi-server.local:
              ftc_user: pi
              ftc_group: pi
    pitop:
      vars:
        ansible_user: pi
        ansible_ssh_pass: pi-top
        ansible_ssh_extra_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
      children:
        pitop4:
          hosts:
            pi-top.local:

    pis:
      children:
        tx_pis:
        pitop:
