all:
  vars:
    ansible_python_interpreter: /usr/bin/python3

  children:
    local:
      hosts:
        localhost:
          ansible_connection: local

    fischertechnik:
      vars:
        ansible_user: pi
        ansible_ssh_pass: raspberry
        ansible_ssh_extra_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
      children:
        tx_pis:
          hosts:
            tx-pi.local:
