---
- hosts: tx_pis
  gather_facts: no

  tasks:
    - name: Ensur /usr/bin/node is absent
      become: yes
      file:
        path: /usr/bin/node
        state: absent

- import_playbook: nvm.yml

- hosts: tx_pis

  vars:
    venv: "{{ansible_user_dir}}/jupyter/venv"

  tasks:
    - name: Install jupyter dependencies
      become: yes
      apt:
        name:
          # Needed by sos
          - libatlas-base-dev
          # GPIO raspberry
          # Normaly installed in base.yml
          - pigpiod
          - gpiod
          # Build jupyter
          - libffi-dev
          # Virtualenv for jupyter-lab
          - virtualenv

    - name: Install jupyter virtualenv
      pip:
        virtualenv: "{{venv}}"
        virtualenv_python: python3
        #executable: pip3
        name:
          - RPI.GPIO
          - setuptools
          - cffi
          - jupyterlab
          - calysto_bash
          - jupyterlab_gitlab
          - jupyterlab-git
          - jupyterlab-spellchecker
          - sos
          - jupyterlab-sos
          - sos-notebook
          - jupyter_micropython_kernel
          - pigpio
          - numpy
          - sshkernel

          #- bash_kernel
          #- RISE
          #- jupyter_contrib_nbextensions
          # pixiedust_node extension
          #- pixiedust_node
          #- matplotlib
          #- jupyterlab_git
          #- jupyterlab_gitlab
          #- octave_kernel
          #- bqplot
          #- pyyaml
          #- sos-papermill
          #- sos-r
          #- markdown-kernel
          #- ipywidgets
          #- jupyros

    - name: Jupyter directoies
      file:
        path: "{{ansible_user_dir}}/{{item}}"
        state: directory
      with_items:
        - notebooks
        - .jupyter

    - name: Config jupyter lab
      template:
        dest: "{{ansible_user_dir}}/.jupyter/{{item}}"
        src: "jupyter/{{item}}"
      with_items:
        - jupyter_lab_config.py
        - jupyter_server_config.json
        - env
      notify:
        - restart_jupyter
        - rebuild_jupyter

    - name: Config service jupyter lab
      become: yes
      template:
        dest: "/lib/systemd/system/jupyter.service"
        src: "jupyter/jupyter.service"
      notify:
        - restart_jupyter
        - rebuild_jupyter

    - name: Ensure sos kernel is installed
      command: "{{venv}}/bin/python -m sos_notebook.install"
      args:
        creates: /usr/local/share/jupyter/kernels/sos
      notify:
        - restart_jupyter
        - rebuild_jupyter
      register: output
      tags:
        - jupyter_base

    - name: Enable sos
      become: yes
      shell: "NODE_OPTIONS=--max_old_space_size=3072 {{venv}}/bin/jupyter labextension install {{item}}"
      with_items:
        - transient-display-data
        - jupyterlab-sos
      when: output is changed

    - name: Ensure jupyter_micropython_kernel kernel is installed
      become: yes
      command: "{{venv}}/bin/python -m jupyter_micropython_kernel.install"
      args:
        creates: /usr/local/share/jupyter/kernels/micropython
      notify:
        - restart_jupyter
        - rebuild_jupyter
      tags:
        - jupyter_base

  handlers:
    - name: restart_jupyter
      become: yes
      service:
        name: jupyter
        enabled: yes
        state: restarted

    - name: rebuild_jupyter
      become: yes
      shell: NODE_OPTIONS=--max_old_space_size=3072 {{venv}}/bin/jupyter lab build
...
