---
- name: Base packages
  hosts: tx_pis

  tasks:
  - name: Configure swap
    become: yes
    lineinfile:
        regexp: "^CONF_SWAPSIZE=*"
        line: "CONF_SWAPSIZE=1024"
        path: /etc/dphys-swapfile
        state: present
    register: dphys
    notify:
        - dphys_swapfile

  - name: Ensure swap file is 1GiB
    stat:
        path: /var/swap
    register: swap_file
    #when_change: False

  - name: Ensure dphys is not running
    become: yes
    service:
        name: dphys-swapfile
        state: stopped
    when: dphys is changed or not swap_file.stat.exists or swap_file.stat.size!=1073741824
    notify:
        - dphys_swapfile

  - name: Ensure swap-file exists
    become: yes
    command: dd if=/dev/zero of=/var/swap count=1024 bs=1MiB
    when: not swap_file.stat.exists or swap_file.stat.size!=1073741824
    notify:
        - dphys_swapfile

  - name: Make swap
    become: yes
    command: mkswap /var/swap
    when: not swap_file.stat.exists or swap_file.stat.size!=1073741824
    notify:
        - dphys_swapfile

  handlers:
  - name: dphys_swapfile
    become: yes
    service:
        name: dphys-swapfile
        state: restarted
        enabled: yes
...
