---
- hosts: pis
  tasks:
    - name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
      become: yes
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade pis
      become: yes
      apt:
        upgrade: dist
      register: dist_upgrade

    - name: Reboot if upgrade
      become: yes
      reboot:
        reboot_timeout: 3600
        pre_reboot_delay: 5
        post_reboot_delay: 10
      when: dist_upgrade is changed

    - name: Remove old packages if upgrade
      become: yes
      apt:
        autoremove: yes
...
