version: '3'
services:
    nodered:
      image: tx-pi/nodered
      depends_on:
        - broker
      privileged: true
      restart: always
      ports:
        - "1880:1880"
      volumes:
        - ./data:/data
      user: 'node-red:node-red'
      group_add:
        - dialout
    broker:
      image: eclipse-mosquitto
      restart: unless-stopped
      command: mosquitto -c /mosquitto-no-auth.conf
      networks:
        - nodered
      ports:
        - "1883:1883"

networks:
  nodered:
