FROM nodered/node-red
RUN npm install \
	node-red-dashboard \
	node-red-node-mysql \
	node-red-node-openweathermap \
	node-red-contrib-fsm \
	node-red-contrib-persistent-fsm \
	node-red-contrib-finite-statemachine \
	node-red-node-arduino \
	node-red-node-pi-gpiod \
	node-red-contrib-home-assistant-websocket \
	node-red-contrib-i2c \
	node-red-node-sqlite
